# Generated by Django 3.1.6 on 2021-02-14 12:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('attr_id', models.IntegerField(primary_key=True, serialize=False)),
                ('usda_tag', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('unit', models.CharField(max_length=10)),
                ('conversion_unit', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('log', models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profileLogMap', to='api.log')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=120)),
                ('unit', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('calories', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('meal_day', models.DateField(default=datetime.date.today)),
                ('meal_time', models.TimeField()),
                ('log', models.ManyToManyField(related_name='mealLog', to='api.Log')),
            ],
        ),
        migrations.AddField(
            model_name='log',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logProfileMap', to='api.profile'),
        ),
        migrations.CreateModel(
            name='Excercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excercise_name', models.CharField(max_length=25)),
                ('met', models.DecimalField(decimal_places=2, max_digits=4)),
                ('duration', models.IntegerField()),
                ('calories_expended', models.IntegerField()),
                ('excercise_day', models.DateField(default=datetime.date.today)),
                ('excercise_time', models.TimeField()),
                ('log', models.ManyToManyField(related_name='excerciseLog', to='api.Log')),
            ],
        ),
        migrations.CreateModel(
            name='DailyValueNutrient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('unit', models.CharField(max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('nutrient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.nutrient')),
            ],
        ),
        migrations.CreateModel(
            name='DailyValueFoodComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('unit', models.CharField(max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('nutrient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.nutrient')),
            ],
        ),
    ]
